### ISSUE TITLE
Invalid protocol scheme when submitting requests

### ISSUE THREAD

**Issue by praveingk** [paraglider-project/paraglider#171]
Below is my config of invd:

```
server: 
  host: "localhost"
  port: 8080
  rpcPort: 8081

cloudPlugins:
  - name: "ibm"
    host: "localhost"
    port: 10002

namespaces: 
  default:
      - name: "ibm"
        deployment: "/ResourceGroupName/paraglider"
tagService:
  host: "localhost"
  port: 6000

```
I get the below error when creating a resource due to absence of `http:// `or `https://` in front of the url
```
% inv resource create ibm vm-test ibm_res.yaml
Resource Created.
tag: 
uri: 
ip: 
Error: Put "localhost:8080/namespaces/default/clouds/ibm/resources/vm-test": unsupported protocol scheme "localhost"
Usage:
  inv resource create <cloud> <resource_name> <resource_description_file> [flags]

Flags:
  -h, --help   help for create

Whoops. There was an error while executing your command: 

```
